### ISSUE TITLE
Lin-CMS前端bug

### ISSUE THREAD

**Issue by zhuxiaoluxiaonuan** [TaleLin/lin-cms-vue#1]
![k9 lk uqnr z0g5p1 874aj](https://user-images.githubusercontent.com/39010432/51366687-c4bb7100-1b21-11e9-9e31-b10cd779e805.png)
上面是bug截图, 浏览器用的谷歌，刚开始打开是没有问题的，然后就各种点击，就出现了上面的情况，这种情况出现过好几次，但是经过多次试验也没找到bug是怎么触发的.

**Comment by vanoneang** [comment]
感谢反馈，我们查找一下

**Comment by GongJS** [comment]
该问题已解决，记得更新下代码哈。
