### ISSUE TITLE
【Feature Request】可以点击logo收起与打开侧边栏

### ISSUE THREAD

**Issue by YpchenLove** [TaleLin/lin-cms-vue#11]
**描述你希望的支持的新功能？**
可以点击logo来打开与收起侧边栏
**你期望的 API 是怎样的？**
![image](https://user-images.githubusercontent.com/26370242/51423867-30284000-1c01-11e9-91aa-c36e1a710962.png)
点击这里弹开侧边栏。
![image](https://user-images.githubusercontent.com/26370242/51423880-4fbf6880-1c01-11e9-84d3-9209920cf162.png)
点击这里可以收起侧边栏

**Comment by YpchenLove** [comment]
github上面图片似乎加载不出来。。。 - -

**Comment by GongJS** [comment]
这个开发者可以根据自己业务需求自己定义，只要绑定一下跟右边按键同样的click函数即可
