### ISSUE TITLE
[bug report]文档路径写错了

### ISSUE THREAD

**Issue by gaojx97** [TaleLin/lin-cms-vue#113]
**重现步骤（可选）：**
![image](https://user-images.githubusercontent.com/15071824/56416874-c59ca400-62c4-11e9-9a7c-d0dbc4126341.png)
前端快速上手界面→页面路由

**期望的结果是什么？**
src/config/stage/

**实际的结果是什么？**
src/router/modules/

**Comment by vanoneang** [comment]
已修改，感谢
