### ISSUE TITLE
【bug report】左侧tabbar过长时显示不全

### ISSUE THREAD

**Issue by gaojx97** [TaleLin/lin-cms-vue#116]
**重现步骤（可选）：**
![image](https://user-images.githubusercontent.com/15071824/56472891-d3098800-6496-11e9-80c1-c74c168a228f.png)

**期望的结果是什么？**
能够滚动

**实际的结果是什么？**
无法看到被遮盖的内容，无法滚动

**Comment by vanoneang** [comment]
已处理，这一阶段的修复优化测试完毕后会合并到master分支，感谢

**Comment by GongJS** [comment]
感谢反馈，已修复。
