### ISSUE TITLE
日志管理未处理空日志的情况

### ISSUE THREAD

**Issue by XiaoDaoGitHub** [TaleLin/lin-cms-vue#120]
**重现步骤（可选）：**
![Snipaste_2019-04-23_21-39-00](https://user-images.githubusercontent.com/30208553/56585458-703bfc00-6610-11e9-8dcc-8e9f0bae004b.png)

**期望的结果是什么？**
建议可以考虑后面做一个全局的错误处理，将错误记录一下，方便重现生产环境中的错误
**实际的结果是什么？**

**Comment by vanoneang** [comment]
已处理
