### ISSUE TITLE
切换tabs时，数据刷新的讨论

### ISSUE THREAD

**Issue by LeeGo486** [TaleLin/lin-cms-vue#122]
**所遇到问题是？**
最近使用好几个vue开发的前端框架，包括lin-cms-vue都有这样的问题。

现在使用lin-cms-vue编辑数据时，如果我切换了标签，在回到编辑页面，数据将被清空。
如果这个页面有20个字段需要填写，那这是不是一个灾难？

在我公司的实际业务中，就被业务部门强力吐槽过。

起初切换标签刷新数据，是为了解决保存后，列表页没有更新的问题。但这样，同样带来了新问题？

**你期望的 API 是怎样的？**

**Comment by quanquan2100** [comment]
这个问题内部并不简单, 并且与具体业务是有强耦合的, 如果一刀切支持缓存, 不光是性能有影响, 更多在于引入了更细致的更新模型和机制. 这也是很多前端框架不接触这个点并且交给开发者自己觉得的原因.

后续团队会讨论是否需要内置支持, 并且如何支持

**Comment by fyzhu** [comment]
可以弄成可配置的，个别模块/页面可以缓存
