### ISSUE TITLE
更新建议

### ISSUE THREAD

**Issue by laolu94678** [TaleLin/lin-cms-vue#13]
1. 希望可以在权限管理中添加 机构管理 , 用户可以分属不同的角色和机构 . 
2. 希望可以在用户管理中 , 增加封禁/恢复 账号的操作.
3. 希望可以新增数据统计的部分 , 前端增加图表(echarts).
4. 希望可以集成elasticsearch(Flask-Elasticsearch) 来进行全文搜索(中文分词)等 . 
5. 希望可以新增一个定时任务处理的模块.
6. 希望可以有一个数据库定时备份(每天0点备份 , 保存本地,并发送备份SQL文件到指定邮箱) . 
7. 希望可以对数据库的备份形成版本管理 , 支持回滚到某一时刻的备份数据.
8. 参数校验似乎并没有校验该参数的类型 , 例如Form中IntegerField , 前端提交其他类型数据(str,list,dict,bool)依然可以提交.是否可以对表单验证器的IntegerField等进行继承封装 , 使之校验类型.
9. 希望可以封装缓存(redis)和接口调用频率限制等.

**Comment by vanoneang** [comment]
感谢反馈，都是很好的建议，cms开发是一个长期过程，也希望能多提PR。

谢谢！
