### ISSUE TITLE
登录失败，“network error”，请检查api是否异常

### ISSUE THREAD

**Issue by liujianfeng1020** [TaleLin/lin-cms-vue#137]
**重现步骤（可选）：**
我安装之后，账号和密码输入正确，super，lin123456，但是每次登录都失败。
提示“network error， 请检查api是否异常”
我检查报错的代码，发现api的地址是：localhost：5000。

于是好奇，我本地并没有部署服务器和数据库啊，这个后台难道不是连接你们远程的服务器吗？还是我们本地的localhost？？

另外我另一台公司的电脑是登录OK的。

失败的log是：
VM26:1 OPTIONS http://localhost:5000/cms/user/login net::ERR_CONNECTION_REFUSED
(anonymous) @ VM26:1
dispatchXhrRequest @ xhr.js?76fc:178
xhrAdapter @ xhr.js?76fc:12
dispatchRequest @ dispatchRequest.js?35c6:59
Promise.then (async)
request @ Axios.js?9b45:51
wrap @ bind.js?51f3:9
post @ http.js?8404:71
_callee$ @ user.js?9fd6:49
tryCatch @ runtime.js?4453:45
invoke @ runtime.js?4453:271
prototype.(anonymous function) @ runtime.js?4453:97
asyncGeneratorStep @ user.js:9
_next @ user.js:11
(anonymous) @ user.js:11
(anonymous) @ user.js:11
getToken @ user.js?9fd6:55
_callee$ @ Login.vue?7463:51
tryCatch @ runtime.js?4453:45
invoke @ runtime.js?4453:271
prototype.(anonymous function) @ runtime.js?4453:97
asyncGeneratorStep @ cjs.js?!./node_modules/_babel-loader@8.0.5@babel-loader/lib/index.js!./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js?!./node_modules/_vue-loader@15.7.0@vue-loader/lib/index.js?!./src/views/login/Login.vue?vue&type=script&lang=js&:9
_next @ cjs.js?!./node_modules/_babel-loader@8.0.5@babel-loader/lib/index.js!./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js?!./node_modules/_vue-loader@15.7.0@vue-loader/lib/index.js?!./src/views/login/Login.vue?vue&type=script&lang=js&:11
(anonymous) @ cjs.js?!./node_modules/_babel-loader@8.0.5@babel-loader/lib/index.js!./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js?!./node_modules/_vue-loader@15.7.0@vue-loader/lib/index.js?!./src/views/login/Login.vue?vue&type=script&lang=js&:11
(anonymous) @ cjs.js?!./node_modules/_babel-loader@8.0.5@babel-loader/lib/index.js!./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js?!./node_modules/_vue-loader@15.7.0@vue-loader/lib/index.js?!./src/views/login/Login.vue?vue&type=script&lang=js&:11
login @ Login.vue?7463:51
(anonymous) @ util.js?306b:82
submit @ Login.vue?05a4:31
invokeWithErrorHandling @ vue.runtime.esm.js?6e6d:1854
invoker @ vue.runtime.esm.js?6e6d:2179
original._wrapper @ vue.runtime.esm.js?6e6d:6911
exception.js?30d7:64 error Error: Network Error
    at createError (createError.js?3494:16)
    at XMLHttpRequest.handleError (xhr.js?76fc:87)
Login.vue?7463:63 Error: Error: Network Error
    at handleError (exception.js?30d7:74)
    at eval (http.js?8404:59)

连接被拒绝

**Comment by ytl003** [comment]
肯定是访问你本地啊，你把apiclone下来运行不就行咯

**Comment by vanoneang** [comment]
lin-cms是完整的CMS解决方案，要前后台都有的，目前官方支持有node和Python两种语言的后端，具体可以查看文档

**Comment by liujianfeng1020** [comment]
> 肯定是访问你本地啊，你把apiclone下来运行不就行咯


f3166fe8
--
是这笔提交将baseurl改为了本地，但是我本地又没有部署服务器，所以出错。
这个提交是昨天刚提上去的。

**Comment by liujianfeng1020** [comment]
> lin-cms是完整的CMS解决方案，要前后台都有的，目前官方支持有node和Python两种语言的后端，具体可以查看文档

https://github.com/TaleLin/lin-cms-vue/commit/f3166fe890fcdd8dabe469659877096749cf6cbc
是这笔提交改了baseurl，是不是作者在提交代码的时候把自己本地的url带上去了。

这样如果本地没有部署的话，这个项目就打不开了哦。你们要不要改回来？？

**Comment by vanoneang** [comment]
本地没有部署是没法正常访问的

**Comment by liujianfeng1020** [comment]
> 本地没有部署是没法正常访问的

是的。但对于仅把前端clone到本地的同学，还是要告诉一下（必须部署后端服务器才行）。
要不就是提供在线的服务器给大家试用。
谢谢

**Comment by vanoneang** [comment]
官方文档有详细介绍~

**Comment by dongxi346** [comment]
开两个命令窗口
一个进入到 starter 项目目录执行： node app/starter.js 
一个进入到 lin-cms-vue-master 项目目录执行： npm run serve

完美登录！
