### ISSUE TITLE
npm run serve 报错

### ISSUE THREAD

**Issue by BJCCSWD** [TaleLin/lin-cms-vue#141]
> lin-cms@0.1.0-beta.1 serve D:\ASBot\frontend\demos\lin-cms-vue
> node script/plugin-get-config.js && vue-cli-service serve

配置插件...
插件配置完成: D:\ASBot\frontend\demos\lin-cms-vue\src\config\stage\plugins.js

 INFO  Starting development server...
 65 6 98% after emitting CopyPlugin

 ERROR  Failed to compile with 2 errors                                                           12:41:16

 error  in ./src/components/layout/User.vue?vue&type=style&index=0&id=b0dd6460&lang=scss&scoped=true&

Module build failed (from ./node_modules/sass-loader/lib/loader.js):

  border-bottom: 1px solid #dae1ed;
            ^
      Expected selector.
    ╷
188 │ .user-dialog /deep/ .el-dialog .el-dialog__header{
    │              ^
    ╵
  stdin 188:14  root stylesheet
      in D:\ASBot\frontend\demos\lin-cms-vue\src\components\layout\User.vue (line 188, column 14)

 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/lib/loader.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/layout/User.vue?vue&type=style&index=0&id=b0dd6460&lang=scss&scoped=true& 4:14-476 14:3-18:5 15:22-484
 @ ./src/components/layout/User.vue?vue&type=style&index=0&id=b0dd6460&lang=scss&scoped=true&
 @ ./src/components/layout/User.vue
 @ ./src lazy ^\.\/.*$ namespace object
 @ ./src/router/home-router.js
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.56.1:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/assets/styles/realize/element-variables.scss

Module build failed (from ./node_modules/sass-loader/lib/loader.js):

  display: none;
                  ^
      Expected selector.
    ╷
440 │ .el-menu--vertical /deep/ .icon-erjizhibiao{
    │                    ^
    ╵
  stdin 440:20  root stylesheet
      in D:\ASBot\frontend\demos\lin-cms-vue\src\assets\styles\realize\element-variables.scss (line 440, column 20)

 @ ./src/assets/styles/realize/element-variables.scss 4:14-254 14:3-18:5 15:22-262
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.56.1:8081/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by vanoneang** [comment]
解决了吗？如果还有问题可以加群咨询

**Comment by wupengxiaobai** [comment]
我这里 npm run serve 17个error  和 sass 有关，怎么重装 还是一样的。。
 error  in ./src/plugins/LinCmsUi/views/tag/Tag.vue?vue&type=style&index=0&id=406c4349&lang=scss&scoped=true&

Module build failed (from ./node_modules/sass-loader/lib/loader.js):

.lin-wrap-ui /deep/ .el-card__body {
            ^
      Expected selector.
  ╷
1 │ .lin-wrap-ui /deep/ .el-card__body{
  │              ^
  ╵
  src\plugins\LinCmsUi\assets\style\container.scss 1:14  @import
  stdin 274:9                                            root stylesheet
      in C:\Users\Administrator\Desktop\projects_w\lin-cms\lin-cms-vue\src\plugins\LinCmsUi\assets\style\container.scss (line 1, column 14)

 @ ./node_modules/vue-style-loader??ref--8-oneOf-1-0!./node_modules/css-loader??ref--8-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--8-oneOf-1-2!./node_modules/sass-loader/lib/loader.js??ref--8-oneOf-1-3!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/plugins/LinCmsUi/views/tag/Tag.vue?vue&type=style&index=0&id=406c4349&lang=scss&scoped=true& 4:14-511 14:3-18:5 15:22-519
 @ ./src/plugins/LinCmsUi/views/tag/Tag.vue?vue&type=style&index=0&id=406c4349&lang=scss&scoped=true&
 @ ./src/plugins/LinCmsUi/views/tag/Tag.vue
 @ ./src lazy ^\.\/.*$ namespace object
 @ ./src/router/home-router.js
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.31.219:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

 error  in ./src/plugins/LinCmsUi/views/form/Select.vue?vue&type=style&index=0&id=2d9234ea&lang=scss&scoped=true&

**Comment by wupengxiaobai** [comment]
我们报的是一样的， 我发现在我自己笔记本上安装是没问题的。 我在笔记本上用的下载命令式 cnpm，不是知道公司的什么鬼

**Comment by vanoneang** [comment]
如果出现node-sass问题，第一先试下

```sh
npm rebuild node-sass
```
如果没反应，切换下npm源到淘宝镜像，然后重试下
