### ISSUE TITLE
前端bug-删除图书后页面原先的数据还在，页面需要刷新

### ISSUE THREAD

**Issue by KDWangBoss** [TaleLin/lin-cms-vue#143]
**重现步骤（可选）：**
> 1. npm start serve
> 2.  添加图书
> 3. 删除图书

**期望的结果是什么？**
> 1. 删除后页面能够去掉删除的数据
> 2. 数据库图书数据被删除，将图书删除操作信息添加到log中

**实际的结果是什么？**
> 点击删除图书后出现如图所示问题
>![图书删除](https://github.com/KDWangBoss/Images/blob/master/LinCMS/%E6%9C%AC%E5%9C%B0%E5%9B%BE%E4%B9%A6%E5%88%A0%E9%99%A4%E9%97%AE%E9%A2%98.jpg?raw=true)

**Comment by vanoneang** [comment]
？删除图书后，有重新获取数据并渲染啊

![image](https://user-images.githubusercontent.com/29253688/57564973-86570400-73e7-11e9-9211-ce9c9d520c0e.png)

**Comment by ronething** [comment]
应该是只剩下一本书 然后点击删除，`this.getBooks()`之后获取到的 status_code 是 404 所以不会重新渲染吧。

**Comment by vanoneang** [comment]
> 应该是只剩下一本书 然后点击删除，`this.getBooks()`之后获取到的 status_code 是 404 所以不会重新渲染吧。

明白了，感谢

**Comment by vanoneang** [comment]
![image](https://user-images.githubusercontent.com/29253688/57760799-e5da4a00-772e-11e9-909b-fef1b156b42b.png)
这样处理下
