### ISSUE TITLE
产品文档的目录结构介绍部分项目重复

### ISSUE THREAD

**Issue by Tzcodejs** [TaleLin/lin-cms-vue#15]
[http://doc.cms.7yue.pro/lin/client/catalog.html#目录结构](url)
![qq 20190122094947](https://user-images.githubusercontent.com/29053523/51507311-4dd8ed80-1e2b-11e9-8783-27fd701cfedf.png)

**Comment by vanoneang** [comment]
感谢反馈，已处理
