### ISSUE TITLE
新增分组成功，但是选择的权限不能保存到数据库。也就是group表有数据，auth表无数据

### ISSUE THREAD

**Issue by zhouyujian** [TaleLin/lin-cms-vue#175]
**重现步骤（可选）：**
新增分组，创建分组成功。查看数据库可发现

原因：fieldlist（stringfield（））得到的auths=把每个字符串拆分了，而不是按逗号拆分出对应的权限名字。（我朋友也是这样，不清楚是环境问题还是什么）

**Comment by vanoneang** [comment]
后端是用的flask还是koa，另外后端的issue可以到对应的仓库提

**Comment by zhouyujian** [comment]
是flask，不好意思。没注意这是前端

**Comment by vanoneang** [comment]
感谢反馈，前端的bug

axios.js 69行
![image](https://user-images.githubusercontent.com/29253688/59159297-2d6bb000-8afa-11e9-88e7-8c1ff9836cec.png)
