### ISSUE TITLE
我吧自己写的文件拷贝进来，一直提示app下面的create_app方法找不到

### ISSUE THREAD

**Issue by zhouyujian** [TaleLin/lin-cms-vue#176]
这并不是cms问题，是我的个人疑问。没地方问，就发在这了。

引入create_app这个方法，明明有的，但是运行确说找不到 cannot import name ‘ create_app’ from app.app‘

请问这是什么原因造成的。刚学python，我朋友买了七月老师的高级编程，我买了flask（下）。所以很多基础问题不是很懂。

**Comment by zhouyujian** [comment]
虚拟机环境和普通pip都尝试了，路径换成 ‘app.app’ 或者 ‘.app’ 都不行

**Comment by zhouyujian** [comment]
查到问题了，互相引入模块的问题。

**Comment by speedywill** [comment]
App
