### ISSUE TITLE
如何解决跨域问题

### ISSUE THREAD

**Issue by movesan** [TaleLin/lin-cms-vue#184]
你好，请问部署到线上环境的时候，出现跨域问题，请问如何基于此项目解决呢？

**Comment by movesan** [comment]
前端：lin-cms-vue
后端：lin-cms-flask

前端项目本地 build后，将dist目录上传到服务器，服务器用nginx做转发，现在已将 domain1 通过nginx成功转发到lin-cms-vue的登录页面；
其中前端 config/index.js 中baseUrl配置域名 domain2，为后端api请求地址，后端lin-cms-flask项目也配置通过nginx转发，
此时点击登录的时候会报Access to XMLHttpRequest at 'domain1' from origin 'domain2' has been blocked by CORS policy 跨域问题，请问这种情况框架中也已经解决了吗

**Comment by vanoneang** [comment]
请问问题解决了吗？如果没解决需要具体截图示例一下

**Comment by movesan** [comment]
@vanoneang 目前此问题已通过 nginx 代理方式解决的

**Comment by vanoneang** [comment]
好的
