### ISSUE TITLE
连续高频率点击登陆时，login请求发送多次

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-cms-vue#19]
**重现步骤（可选）：**
连续高频率点击登陆时
会多次发出login请求
**期望的结果是什么？**
点击登陆时，在未拿到response不能重复发送请求

这里建议加个loading效果，或者对请求进行过滤

**Comment by GongJS** [comment]
已用节流函数限制重复发起请求，目前设置的间隔为2秒。
