### ISSUE TITLE
用pm2 来运行koa 报错

### ISSUE THREAD

**Issue by kuwo2016** [TaleLin/lin-cms-vue#192]
按照文档的步骤，可以将koa运行起来，ℹ loading a route: /cms/user/                                                                                                                                                                           13:59:12
ℹ loading a route: /cms/user/change_password                                                                                                                                                            13:59:12
ℹ loading a route: /cms/user/refresh                                                                                                                                                                    13:59:12
ℹ loading a route: /cms/user/auths                                                                                                                                                                      13:59:12
ℹ loading a route: /cms/user/information                                                                                                                                                                13:59:12
ℹ loading a route: /cms/user/avatar                                                                                                                                                                     13:59:12
ℹ loading a router instance :bookApi from file: /data/release/wxcms/app/api/v1/book.js                                                                                                                  13:59:12
ℹ loading a route: /v1/book/:id                                                                                                                                                                         13:59:12
ℹ loading a route: /v1/book/                                                                                                                                                                            13:59:12
ℹ loading a route: /v1/book/search/one                                                                                                                                                                  13:59:12
ℹ loading a route: /v1/book/                                                                                                                                                                            13:59:12
ℹ loading a route: /v1/book/:id                                                                                                                                                                         13:59:12
ℹ loading a route: /v1/book/:id (repeated 1 times)                                                                                                                                                      13:59:12
ℹ loading a route: /v1/book/                                                                                                                                                                            13:59:12
2019-07-03 13:59:12,917 INFO 10397  --- [VM_0_13_centos] - listening at http://localhost:5000并得到，“心上无垢，林间有风"提示，但是，用pm2来运行时报错，/root/.pm2/logs/starter-out.log last 15 lines:
/root/.pm2/logs/starter-error.log last 15 lines:
1|starter  | { Error: ENOENT: no such file or directory, scandir '/data/release/wxcms/app/app/config'
1|starter  |     at Object.fs.readdirSync (fs.js:904:18)
1|starter  |     at applyConfig (/data/release/wxcms/app/starter.js:9:20)
1|starter  |     at run (/data/release/wxcms/app/starter.js:18:3)
1|starter  |     at Object.<anonymous> (/data/release/wxcms/app/starter.js:27:1)
1|starter  |     at Module._compile (module.js:653:30)
1|starter  |     at Object.Module._extensions..js (module.js:664:10)
1|starter  |     at Module.load (module.js:566:32)
1|starter  |     at tryModuleLoad (module.js:506:12)
1|starter  |     at Function.Module._load (module.js:498:3)
1|starter  |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:27:21)
1|starter  |   errno: -2,
1|starter  |   code: 'ENOENT',
1|starter  |   syscall: 'scandir',
1|starter  |   path: '/data/release/wxcms/app/app/config' }

PM2      | App [starter:1] exited with code [0] via signal [SIGINT]
PM2      | App [starter:1] starting in -fork mode-
PM2      | App [starter:1] online
1|starter  | { Error: ENOENT: no such file or directory, scandir '/data/release/wxcms/app/app/config'
1|starter  |     at Object.fs.readdirSync (fs.js:904:18)
1|starter  |     at applyConfig (/data/release/wxcms/app/starter.js:9:20)
1|starter  |     at run (/data/release/wxcms/app/starter.js:18:3)
1|starter  |     at Object.<anonymous> (/data/release/wxcms/app/starter.js:27:1)
1|starter  |     at Module._compile (module.js:653:30)
1|starter  |     at Object.Module._extensions..js (module.js:664:10)
1|starter  |     at Module.load (module.js:566:32)
1|starter  |     at tryModuleLoad (module.js:506:12)
1|starter  |     at Function.Module._load (module.js:498:3)
1|starter  |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:27:21)
1|starter  |   errno: -2,
1|starter  |   code: 'ENOENT',
1|starter  |   syscall: 'scandir',
1|starter  |   path: '/data/release/wxcms/app/app/config' }
pm2上其它项目运行正常。请教一下，是我那里没有配置对，还是其它问题？

**Comment by vanoneang** [comment]
解决了吗？

**Comment by kuwo2016** [comment]
> 解决了吗？
只能说很奇怪，我给lincms vue前端域名，wxcms.jisuweixin.com 配了一个ssl证书，然后，在第一次打开时，google浏览器，拦截了什么插件，然后，地址栏上显示https证书错误，尝试登录后台，报后台api异常，去后端控制台查询日志，无报错，然后，点击允许google拦截的插件，再次尝试登录，就可以登录成功，请问，这是不支持ssl证书，还是要做兼容？

**Comment by kuwo2016** [comment]
问题已经解决了，真奇怪，为了方便，我就我直接在我的cenot7.3的服务器上直接写代码了，然后回家用本地开发环境，重新npm run build 又生成了一次，就没有上述所有问题了。线上和线下的开发环境，都是一致的。
