### ISSUE TITLE
SequelizeConnectionError: Unknown database 'lin-cms'

### ISSUE THREAD

**Issue by kingrome2017** [TaleLin/lin-cms-vue#197]
'use strict';

module.exports = {
  db: {
    database: 'lin-cms',
    host: 'localhost',
    dialect: 'mysql',
    dialectOptions: {
      socketPath: '/tmp/mysql.sock' // 指定套接字文件路径
    },
    port: 3306,
    username: 'root',
    password: 'fljzjk521',
    logging: false,
    timezone: '+08:00'
  },
  secret:
    '\x88W\xf09\x91\x07\x98\x89\x87\x96\xa0A\xc68\xf9\xecJJU\x17\xc5V\xbe\x8b\xef\xd7\xd8\xd3\xe6\x95*4'
};

**Comment by vanoneang** [comment]
数据库建了吗

**Comment by kingrome2017** [comment]
mysql支持自动创建吗？

**Comment by vanoneang** [comment]
不能，数据库是要自己手动创建的，数据表可以通过ORM来创建

**Comment by kingrome2017** [comment]
那mysql 从官方网站下载可以吗？我的电脑是mac 有推荐的教程吗？

**Comment by vanoneang** [comment]
可以从官网下载
