### ISSUE TITLE
富文本编辑器以及编辑器内图片上传功能的实现

### ISSUE THREAD

**Issue by wlf36** [TaleLin/lin-cms-vue#2]
富文本编辑器以及编辑器内图片上传功能的实现

**Comment by vanoneang** [comment]
感谢反馈

**Comment by PedroGao** [comment]
有同样需求的同学们，可以在这个issue的下面讨论一下，你们需要怎么样的富文本和图片上传的功能机制。
如果有具体的参考样例那就更好了。

**Comment by wlf36** [comment]
在vue里使用过tinymce，就是长传图片速度慢

**Comment by yujiak** [comment]
希望可以采用切片上传的方式，这样上传大图片、大文件或视频不会受到大小限制

**Comment by ronething** [comment]
我觉得需要一个 markdown 编辑器。 😁

**Comment by mhkz** [comment]
首先肯定作者的作品，同时希望能增加markdown编辑器

**Comment by vanoneang** [comment]
本周发版
