### ISSUE TITLE
refresh token获取失败

### ISSUE THREAD

**Issue by YpchenLove** [TaleLin/lin-cms-vue#200]
**使用lin-cms-koa启动后端服务，打开lin-cms-vue登录一直报refresh token获取失败**

**期望的结果是什么？**
正常登录
**实际的结果是什么？**
登录失败，并且在network里发送了79次无意义的请求，

**Comment by YpchenLove** [comment]
![Uploading A(WJLN0[SLTFC6OF()%H@@Q.png…]()

**Comment by vanoneang** [comment]
什么版本，这个问题早就修复了
