### ISSUE TITLE
建议：标签页切换时状态需要保存。

### ISSUE THREAD

**Issue by liicos** [TaleLin/lin-cms-vue#215]
**描述你希望的支持的新功能？**
比如说表单填写后，切换到其它标签页，再切回来，表单内容全没了。 这样非常影响用户体验~ 
之前有人提过 ：https://github.com/TaleLin/lin-cms-vue/issues/122#issue-437051742

我觉得这个功能的优先级应该是比较高的。

**Comment by quanquan2100** [comment]
这个涉及keepalive, 这个机制如果一刀切的上, 会引起另外很多的问题, 比如更新时机以及不同的更新机制, 所以目前是交给开发者自主决定. 

后续团队会讨论是否内置该机制, 以及以何种方式提供开发者使用
