### ISSUE TITLE
关于支持右键tabs显示下拉菜单的建议

### ISSUE THREAD

**Issue by ChenJinchuang** [TaleLin/lin-cms-vue#217]
**描述你希望的支持的新功能？**
右键tabs可以弹出个下拉小菜单，支持一些批量或者页面操作，目前项目当tabs打开很多的时候，操作体验不佳。。
**你期望的 API 是怎样的？**
![image](https://user-images.githubusercontent.com/49727104/61688040-83b54b00-ad56-11e9-85e8-c017cf1b6fd6.png)

**Comment by quanquan2100** [comment]
您的反馈已收到, 之后会加入到系统中

**Comment by vanoneang** [comment]
done
