### ISSUE TITLE
当出现一个错误的时候，弹出多条提示框，希望统一一下标准

### ISSUE THREAD

**Issue by JoeyGaojingxing** [TaleLin/lin-cms-vue#220]
**重现步骤（可选）：**
比如，api超时

**期望的结果是什么？**
弹出一条即可，而且全局统一

**实际的结果是什么？**
![image](https://user-images.githubusercontent.com/15071824/61973613-0409d380-b017-11e9-92c1-e710cb6088ed.png)

**Comment by vanoneang** [comment]
目前的设定是业务异常与网络异常（或者无response）区分开，如果有需求可以自行修改：

位置： src/lin/plugins/axios.js

_axios.interceptors.response.use()
