### ISSUE TITLE
【Feature Request】一键关闭历史浏览

### ISSUE THREAD

**Issue by vanoneang** [TaleLin/lin-cms-vue#224]
**描述你希望的支持的新功能？**

**你期望的 API 是怎样的？**

**Comment by mslhly** [comment]
springboot 后台




| |
少龙
|
|
邮箱：mslhly@163.com
|

签名由 网易邮箱大师 定制

在2019年08月14日 23:07，Evan Wang 写道：

描述你希望的支持的新功能？

你期望的 API 是怎样的？

**Comment by vanoneang** [comment]
已完成~
