### ISSUE TITLE
修改侧边栏宽度的时候，显示效果和实际配置

### ISSUE THREAD

**Issue by YpchenLove** [TaleLin/lin-cms-vue#226]
**重现步骤（可选）：**
1，将lin-variables.scss 中的$sidebar-width: 175px; 改为200px
2，查看页面的侧边栏效果，发现存在展示效果不符合预期的现象，
3，$sidebar-width应该是只在sidebar组件引入了，他的父级容器应该没有引入

图片无法上传！。。要不你复现下看看

**Comment by 7insummer** [comment]
上次晚上开会讨论了要将默认的宽度增加 15px，默认的是有点窄了。当时在浏览器里修改的没问题，等一飞看看

**Comment by YpchenLove** [comment]
$sidebar-width: 175px; 这个变量应该好几个地方没有引入，所以当我修改了lin-variables.scss里的配置项的时候 就出现bug了。我跟一飞说了
