### ISSUE TITLE
修改密码业务问题

### ISSUE THREAD

**Issue by Jokky6** [TaleLin/lin-cms-vue#23]
我觉得修改密码时，用户应该输入下原始的密码，防止恶意修改密码！
而且当密码是原始密码的时候，不应该发PUT请求
我觉得这个细节值得优化一下

**Comment by vanoneang** [comment]
感谢反馈

**Comment by GongJS** [comment]
这个是这样的，如果是管理员修改其他用户的密码，是不需要原始密码的；如果是管理员或者用户自己修改自己的密码，需要通过右上角的人物头像跳转到修改密码的页面，这时候是需要输入原始密码才能修改的。
