### ISSUE TITLE
你好，请问下怎么修改项目里面的iconfont字体图标呢

### ISSUE THREAD

**Issue by KDWangBoss** [TaleLin/lin-cms-vue#231]
**重现步骤（可选）：**
需求：从iconfont字体图标中获取字体图标，需要添加到项目中。
问题：如果使用自定义iconfont会覆盖原有的iconfont，请问下这个要怎么处理呢

**Comment by vanoneang** [comment]
你可以额外引入一个你自己的iconfont.css文件

**Comment by KDWangBoss** [comment]
明白了，非常感谢
