### ISSUE TITLE
对于 lin-cms-vue 的前端组件库多图上传

### ISSUE THREAD

**Issue by Guo-Hongfu** [TaleLin/lin-cms-vue#232]
七月老师，您好。
我在使用 vue 的多图组件的时候，我开启了sortable参数排序，然而只是对图片位置进行了调整，没有一个指定的参数能明了的说明哪张图片在前在后，我的想法是图像的参数再加一个属性sort，可以记录当前图片索引，当图像的位置被更改时，该参数对应的值也被更改。

以上，就是对组件的疑问。如有不妥之处，还望老师多多包涵。也希望老师不吝赐教。

**Comment by quanquan2100** [comment]
多图上传组件是可以在每个图片上添加一个id的, 传入和输出都是数组, 数组对应的排序后的图片组.
你可以根据 id 获取图片移动到第几个, 如果没有传入 id, 直接判断图片地址也可以
