### ISSUE TITLE
当上传文件遇到需要刷新令牌的时候出现了content-type错误

### ISSUE THREAD

**Issue by Dm-China** [TaleLin/lin-cms-vue#233]
nodejs.Error: Content-Type must be multipart/*

**Comment by quanquan2100** [comment]
是单纯使用上次文件接口还是说在使用图像上传组件的时候遇到的?

**Comment by Dm-China** [comment]
@quanquan2100 使用图像上传组件的时候

**Comment by vanoneang** [comment]
麻烦描述清晰一些，是图像上传时，assess_token过期吗？

**Comment by Dm-China** [comment]
@vanoneang 是的，assess_token过期的时候，图像上传就出现错误，后台显示: Content-Type must be multipart/*。使用的是Lin-ui的多图上传组件

**Comment by vanoneang** [comment]
能贴一下代码吗？ network和你写的代码

**Comment by Dm-China** [comment]
@vanoneang 
<img width="1442" alt="WX20190929-171228@2x" src="https://user-images.githubusercontent.com/50285822/65829892-bc384e80-e2dc-11e9-8eaf-e85727c57001.png">
<img width="834" alt="WX20190929-171300@2x" src="https://user-images.githubusercontent.com/50285822/65829894-c3f7f300-e2dc-11e9-9de5-a5bc72f9b83f.png">

**Comment by Dm-China** [comment]
@vanoneang 你把assess_token设置成几分钟，等过期后再去上传图像

**Comment by vanoneang** [comment]
感谢反馈，我们调试下

**Comment by vanoneang** [comment]
感谢反馈！将 `axios.js`中重发的参数改为上次请求的 Request Config：

![image](https://user-images.githubusercontent.com/29253688/66263969-15e5cf00-e82f-11e9-82d7-976d0e755932.png)
