### ISSUE TITLE
有一个bug好像

### ISSUE THREAD

**Issue by Guo-Hongfu** [TaleLin/lin-cms-vue#236]
关于`lin-table.vue`的一个小Bug, 路径是：`src/components/base/table/lin-table.vue`第171行处：
```
methods: {
    // 开发者自定义的函数
    buttonMethods(func, index, row) {
      const _this = this
      const { methods } = this.$options
      methods[func](_this, index, row)
    },
   ...
```

获取开发者自定义的函数，不应该是从 `this.$options`，这个this应该是 lin-table，而应该写成:
```
 // 开发者自定义的函数
    buttonMethods(func, index, row) {
      const _this = this.$parent
      const { methods } = _this.$options
      methods[func](_this, index, row)
    },
```
这样才能获取到开发者自定义的函数吧。因为 lin-table 写到页面中就是一个子组件了。

**Comment by vanoneang** [comment]
@GongJS

**Comment by GongJS** [comment]
这种写法，就是要求开发者把自定义的函数写在lin-table这个组件里面的。

**Comment by Guo-Hongfu** [comment]
这样的话，lin-table 会越来越臃肿哇，比较 lin-table  是一个子组件，会在很多地方引用。

**Comment by vanoneang** [comment]
> 这样的话，lin-table 会越来越臃肿哇，毕竟 lin-table 是一个子组件，会在很多地方引用。

所以现在不推荐使用lin-table，用基础的el-table自己组装复杂业务，lin-table这种思路不适合做开源组件，做一些针对业务的封装还行

**Comment by Guo-Hongfu** [comment]
OK~
