### ISSUE TITLE
使用tinymce后，打包上线出现了js，css资源未找到404

### ISSUE THREAD

**Issue by KDWangBoss** [TaleLin/lin-cms-vue#239]
**重现步骤（可选）：**
> 在 vue.config.js 中修改publicPath: '/dist',
> `npm run build`

**期望的结果是什么？**
> 能够正常加载js和样式文件

**实际的结果是什么？**
> 项目其他样式文件可以正常加载出来，但富文本的不可以
> `GET 域名/js/skins/content/default/content.css net::ERR_ABORTED 404 (Not Found)`
> `chunk-64e12ad6.a1c2d3e9.js:1 GET 域名/js/skins/content/default/content.css net::ERR_ABORTED 404 (Not Found)`

**Comment by vanoneang** [comment]
@GongJS

**Comment by GongJS** [comment]
更新一下到最新的版本，再重新打包部署

**Comment by vanoneang** [comment]
#241

**Comment by KDWangBoss** [comment]
好的
