### ISSUE TITLE
前端问题

### ISSUE THREAD

**Issue by DOVER123** [TaleLin/lin-cms-vue#243]
想找一个node的cms好久了，发现这个真的很棒，我的问题是，如果我要进行前端的展示，是需要再起一套服务来进行数据的展示吗？
比如官网上的的例子，在cms里面建了一个图书的业务，加一个一本书叫《lin-cms文档》， 那么需要有一个给非管理用户看的、专门来展示各种图书的页面，就会增加一个《lin-cms文档》，那么在您的这套cms里面，是把给非管理用户展示的页面的服务和lin-cms写在一起，起一个服务好？还是另外再起一个服务，两者调用同一个数据库好？

**Comment by vanoneang** [comment]
你说的`非管理用户`是类似网站展示的C端用户吗？ `lin-cms`是后台管理系统，当然C端的逻辑页可以跟CMS的 API 写在一起，也可以分开
