### ISSUE TITLE
循环引用

### ISSUE THREAD

**Issue by fyzhu** [TaleLin/lin-cms-vue#250]
**重现步骤（可选）：**
npm run serve

**期望的结果是什么？**

**实际的结果是什么？**
![image](https://user-images.githubusercontent.com/5175751/67927143-d5d9f800-fbf2-11e9-9d41-985eb3ee9eb3.png)

**Comment by vanoneang** [comment]
api请求可以直接使用 `this.$axios`，有些代码是考虑兼容最初版本一些写法，可自行删除
