### ISSUE TITLE
如何保证一致的代码风格

### ISSUE THREAD

**Issue by zhangxiaoshang** [TaleLin/lin-cms-vue#256]
### 开发环境
vscode + eslint + prettier
eslint 对代码风格进行检查
prettier对代码进行格式化

### 问题
当对项目代码进行改动后，保存时触发vscode自动格式化代码功能，这时候vscode会使用prettier对代码进行格式化，但是格式化之后的代码不能通过项目中.eslintrc.js 配置的规则校验。
问题多是：`Missing trailing comma` 、`Extra semicolon`、`Strings must use singlequot`

### 期望
vscode自动格式化代码后，代码能够通过eslint的校验

### 我所做的尝试
- 1 修改vscode的配置，如 ` "prettier.singleQuote": true` 但是没有效果，格式化之后还是双引号。
- 2 修改 .eslintrc.js 使eslint的规则适应格式化之后的代码，但是这样就不能和源码保持一致的风格，这种方式最大的问题是要重新格式化原项目所有文件。

### 希望得到什么样的帮助
1. 如果项目团队也同样使用了vscode的自动格式代码的功能，希望能够提供一份vscode的配置。
2. 如果项目团队不是使用vscode的自动格式化功能，那么开发团队是如何保证一致的代码风格的？

**Comment by zhangxiaoshang** [comment]
vscode不用 prettier 的话，可是设置vscode的配置

```json
{
  "editor.formatOnSave": false,
  "eslint.autoFixOnSave": true,
}
```

即保存代码时不使用自动格式化的功能，使用eslint的代码修复功能

**Comment by vanoneang** [comment]
团队有使用一套统一的 vue-format 和 vscode 配置，但为保证大家风格统一可以使用一些库辅助，感谢PR。
