### ISSUE TITLE
关于定义了模型层(models)的toJSON方法后，在数据处理层使用setDataValue方法后不能得到预期添加的字段信息。

### ISSUE THREAD

**Issue by tclcm1987** [TaleLin/lin-cms-vue#280]
如题。在models层定义了toJSON方法后的确能方便得到需要返回的数据格式，但是对于需要跨表查询，然后手动加入返回数据中的情况就变麻烦了，使用setDataValue方法添加属性，依然不会显示新加入的属性值

**Comment by PedroGao** [comment]
意思是：由于定义了toJSON方法后，覆盖了基础Model的toJSON方法，导致setDataValue添加属性值后，toJSON无法得到set的值？

**Comment by PedroGao** [comment]
![image](https://user-images.githubusercontent.com/23636473/70774353-f3cf7680-1db4-11ea-8eda-c70bcafb2077.png)

我刚才看了一下sequelize的源码，基础Model的toJSON方法确实还挺有用的，如果你真的需要的话，可以直接覆盖库里面的toJSON方法，伪代码如下：

```js
UserModel.toJSON = function() {
     return cloneDeep(
        this.get({ plain: true })
     )
```
后续我们会把model的定义直接放在demo里面，方便用户修改。
现在确实诸多不便，抱歉了。

**Comment by tclcm1987** [comment]
好的，谢谢指教
