### ISSUE TITLE
请问下 后端java版本什么时候出

### ISSUE THREAD

**Issue by guojiaxing1995** [TaleLin/lin-cms-vue#283]
**描述你希望的支持的新功能？**

**你期望的 API 是怎样的？**

**Comment by vanoneang** [comment]
正在测试了，莫着急

**Comment by yangtao0726** [comment]
> 正在测试了，莫着急

请问是springboot  + vue 前端后端分离那种吗223

**Comment by vanoneang** [comment]
> > 正在测试了，莫着急
> 
> 请问是springboot + vue 前端后端分离那种吗223

是的，已经发布了，查看林间有风的团队仓库可以找到。
