### ISSUE TITLE
多图上传组件在上传图片后数据丢失

### ISSUE THREAD

**Issue by Li-Zhi-Wei** [TaleLin/lin-cms-vue#290]
**重现步骤（可选）：**
图片上传成功后该组件的数据会受其他操作影响，并被清空
**期望的结果是什么？**
多图上传组件保持自己的数据
**实际的结果是什么？**
![运行截图1](https://user-images.githubusercontent.com/44724651/74604247-f6bd4f00-50f6-11ea-97fb-e8b8370e4d72.png)
![运行截图2](https://user-images.githubusercontent.com/44724651/74604380-5bc57480-50f8-11ea-938b-7ad846ae49f5.png)

**Comment by quanquan2100** [comment]
你修改其它表单字段的时候, 是不是把图片初始化的值也更新了

**Comment by Li-Zhi-Wei** [comment]
> 
> 
> 你修改其它表单字段的时候, 是不是把图片初始化的值也更新了

已经找到bug了，是我自己写法有错误

```
<div v-for="(item,index) in temp.items" :key="index">
    <!--省略-->
    <upload-imgs ref="uploadEle" :max-num="1" :value="[bannerItemImg[index]]" :remote-fuc="uploadImage"/>
</div>
```
初始值为 `bannerItemImg = []`
此时 bannerItemImg[index] = undefined 
[bannerItemImg[index]] = [undefined]
而非文档中写的 []
从而造成了此bug
改正后可以正常运行
