### ISSUE TITLE
请教一个问题，是关于数据查询的

### ISSUE THREAD

**Issue by tclcm1987** [TaleLin/lin-cms-vue#293]
发现一个问题：
我发现使用Sequelize在条件查询时即使不在where里面加入delete_time: null这样的限制条件，SQL查询语句里面依然会加入WHERE (`office`.`delete_time` IS NULL)这样的条件。
我想问一下这是Sequelize的通病还是在lin-cms-vue才会发生的事情？如何避免这种情况？

**Comment by tclcm1987** [comment]
> 发现一个问题：
> 我发现使用Sequelize在条件查询时即使不在where里面加入delete_time: null这样的限制条件，SQL查询语句里面依然会加入WHERE (`office`.`delete_time` IS NULL)这样那样的条件。
> 我想问一下这是Sequelize的通病还是在lin-cms-vue才会发生的事情？如何避免这种情况？

**Comment by smileShirmy** [comment]
这是因为 lin-cms-koa 中设置了 paranoid: true，在删除的时候是软删除，不是硬删除，因此查询的时候都会加上你提到的查询条件以避免查到那些删除的数据。官方文档提供了一些方法来解决这个问题，详细你可以看：[sequelize paranoid](https://sequelize.org/master/manual/paranoid.html)
