### ISSUE TITLE
替换阿里  iconfont 图标

### ISSUE THREAD

**Issue by guojiaxing1995** [TaleLin/lin-cms-vue#295]
在做自己的项目时，想更新下icon，到iconfont官网将图标加入项目下载下来替换了iconfont.css文件，但是lin框架自带的icon就都找不到了。
请教下，现在想在新增icon的同时保留lin框架的icon，要怎么做？

**Comment by vanoneang** [comment]
[参考文档](http://doc.cms.7yue.pro/lin/client/components/icon.html#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
