### ISSUE TITLE
在低分辨率的设备上可以看到整个页面是不会滚动的 但是AppMain里面的内容可以scroll 

### ISSUE THREAD

**Issue by shaonianla1997** [TaleLin/lin-cms-vue#296]
**描述你希望的支持的新功能？**
请问七月老师这种效果是怎么实现的 或者需要什么配置吗
**你期望的 API 是怎样的？**

**Comment by vanoneang** [comment]
是否滚动及滚动条可以根据 `overflow-y` `::-webkit-scrollbar` 两个CSS属性调节。
