### ISSUE TITLE
富文本高度太低，而且文字多的时候只能通过右侧的滑轮滚动，不能在富文本内部通过鼠标滚轮滚动查看内容。

### ISSUE THREAD

**Issue by marysis** [TaleLin/lin-cms-vue#3]
**重现步骤（可选）：**

**期望的结果是什么？**

**实际的结果是什么？**

**Comment by vanoneang** [comment]
感谢反馈

**Comment by vanoneang** [comment]
非常感谢，这确实是个bug，[框架引入了BScroll造成](https://github.com/ustbhuangyi/better-scroll/issues/633)，之后我们会给出解决方案。

**Comment by vanoneang** [comment]
已解决，整体舞台框架移除了BScroll，不过封装的scroll组件仍然保留
