### ISSUE TITLE
线上文档 dom 权限控制 v-promisson  

### ISSUE THREAD

**Issue by guojiaxing1995** [TaleLin/lin-cms-vue#302]
线上文档展示为 v-promisson 控制无权限操作dom的显示与隐藏，使用发现v-promisson 无效，需要使用v-auth才可以。
文档错误 请更新文档

**Comment by fujiale33** [comment]
您好，您使用的后端是flask版本吧？对应前端的 2.x 版本。因为 3.x 对部分命名进行了更新，随之文档也更新成了新的命名。我们会在文档中增加提示。
另外，等后面 lin-cms-java 相对稳定后会升级 lin-cms-flask 的。

**Comment by guojiaxing1995** [comment]
是flask  
这个2.x 3.x 是vue的版本吧
如果之后我同时还想用java版本和flask版本都去开发并共用1套前端，是不是 前端和flask版本都要去更新，还是说只需要flask版本更新就行。
由于目前我本地前端改了部分源码，所以更新会比较麻烦。
flask版本更新后应该不会对业务功能有影响吧，希望出一个更新说明
感谢

**Comment by fujiale33** [comment]
对，是的。flask 和 前端都要更新，这种工程类项目很难做到无痛升级。所以您升级版本的话如果不是对源码很了解都会费一番功夫。
如果项目不是很紧急的话，建议后端先使用 java 版本，这个版本是跟进的最快的。文档上的内容也是最准确的。

**Comment by guojiaxing1995** [comment]
好的  感谢
flask 和 前端 升级后在版本那里标注下
