### ISSUE TITLE
线上部署文档

### ISSUE THREAD

**Issue by sunniejs** [TaleLin/lin-cms-vue#307]
在文档中没有看到如何部署在服务器上，希望能够添加

**Comment by vanoneang** [comment]
线上部署每个公司的要求不同，有些是直接上 VM，有些是走 CI/CD，还有些别的，开源项目不会提供部署相关的内容。

**Comment by linheqin** [comment]
是不是属于node后端部署。因为我直接把代码上传服务器，运行不了什么的
