### ISSUE TITLE
表格中的时间戳转换和索引序号问题

### ISSUE THREAD

**Issue by xiaoyunjie** [TaleLin/lin-cms-vue#310]
**重现步骤（可选）：**
 tableColumn: [
        { prop: 'index', label: '序号' },    // 添加了index，但是表格显示没有数据，空的
        { prop: 'username', label: '注册名', width: 300 },
        { prop: 'nickname', label: '姓名', width: 300 },
        { prop: 'create_time', label: '创建时间', width: 300 },  //时间戳不知道如何转换，formatter如何使用
        { prop: 'summary', label: '简介' }
      ],
看到在 Log.vue 中可以 {{log.time | dateTimeFormatter}}
想知道在表格这里如何操作？

**期望的结果是什么？**
期望时间戳不是unix时间而是转换后的时间  格式：2020-04-22 15:09:12

**实际的结果是什么？**
![image](https://user-images.githubusercontent.com/18340924/80054340-8ea14400-8551-11ea-9d03-f00361534bff.png)

**Comment by vanoneang** [comment]
可以在取得数据后用 js 循环处理一遍，lin-table 这种再次封装的组件本身就有局限性，只适用于一些简单场景，自己的业务还是建议直接使用 el-table。
