### ISSUE TITLE
0.3.4版本的表格渲染的数据和标题不对齐

### ISSUE THREAD

**Issue by 270686992** [TaleLin/lin-cms-vue#313]
**重现步骤（可选）：**

**期望的结果是什么？**
使用了springboot版本的cms后台和最新的vue版本cms前台,表格的标题应该和数据是对齐的。
**实际的结果是什么？**
表格标题和数据不对齐,如下图:

<img src="http://image.xilikeli.cn/1.png" width="250"/>

使用了0.2.x版本的运行了后是对齐的,如下图,但0.2.x版本对接springboot有问题，希望能处理一下0.3.4版本的这个问题

<img src="http://image.xilikeli.cn/2.png" width="250"/>

**Comment by vanoneang** [comment]
1. springboot 是后来完成的版本，初始对接的就是 vue 的0.3.0
2. 在[演示网站](http://face.cms.7yue.pro/#/book/list)上没有发现这个对齐的问题，如果确实存在的话，可以打开 Chrome 的调试工具看下 CSS 样式是否有被覆盖的地方。

**Comment by 270686992** [comment]
已解决,修改 padding-left 为以下的值后对齐了:
<img width="auto" src="http://img-blog.csdnimg.cn/20200429101246265.png">

**Comment by vanoneang** [comment]
好的
