### ISSUE TITLE
更改nickname名字，前端不会即时生效

### ISSUE THREAD

**Issue by ToWeLong** [TaleLin/lin-cms-vue#316]
前端版本：0.3.5  
后端koa: 0.3.3

**重现步骤（可选）：**
更改nickname名字，前端不会即时生效，重新退出然后再登录才生效
**期望的结果是什么？**
更改nickname名字，前端会即时生效
**实际的结果是什么？**
![Snipaste_2020-05-05_16-05-33](https://user-images.githubusercontent.com/41502558/81046133-45a2a580-8eea-11ea-8f21-2b49bbab0e7d.png)

**Comment by ToWeLong** [comment]
不是在数据库中直接改的

**Comment by vanoneang** [comment]
1. 看下 [http://face.cms.7yue.pro/](http://face.cms.7yue.pro/) 演示网站是正常的；
2. 修改头像后，会再次调用 `cms/user/information` 接口，然后更新 vuex 中的 user 对象。

**Comment by ToWeLong** [comment]
@vanoneang 演示网站我也看到了会更改的，但是我最新拉下来的代码就不会改不知道为什么
