### ISSUE TITLE
关于案例

### ISSUE THREAD

**Issue by act2009** [TaleLin/lin-cms-vue#318]
**描述你希望的支持的新功能？**

能否提供案例http://sleeve.7yue.pro/ 的直接样式模版下载呢？很多页面很符合需求，只能自己参考着写吗？能否提供下载

**你期望的 API 是怎样的？*
暂无

**Comment by vanoneang** [comment]
你好，http://sleeve.7yue.pro/ 属于商业项目，无法提供源码。
