### ISSUE TITLE
TS 引入报错问题 lin-mizar(验证器模块)

### ISSUE THREAD

**Issue by lz-web** [TaleLin/lin-cms-vue#319]
**重现步骤（可选）：**
mport { LinValidator, Rule } from "lin-mizar"
class RegisterValidator extends LinValidator {
id: Rule;
constructor() {
super();
this.id = new Rule("isInt", "id必须为正整数", { min: 1 });
}
}
export { RegisterValidator }

import { LinRouter } from "lin-mizar";
import { loginRequired } from "../middleware/jwt";
import { RegisterValidator } from "../validators/user.validate";
const userRouter = new LinRouter({
prefix: '/medical/data'
});
userRouter.linPost(
'name',
'/register',
{},
loginRequired,
// userLogger('管理员新建了一个用户'),
async ctx => {
let test = new RegisterValidator().validate(ctx)
console.log(test)
ctx.json({
code: 10000,
msg: '成功!'
});
}
);
export {
userRouter
};

报错行数: let test = new RegisterValidator().validate(ctx)
报错信息:
nodejs.TypeError: Class constructor LinValidator cannot be invoked without 'new'
希望能尽快解决谢谢
**期望的结果是什么？**
可以正常引入 使用lin-mizar的验证模块即可
**实际的结果是什么？**

**Comment by vanoneang** [comment]
change your `target` attribute to `ES2015` or above in `tsconfig.json` file .

```ts
{
  "compilerOptions": {
    "target": "ES2015"  /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019' or 'ESNEXT'. */
}
```

**Comment by lz-web** [comment]
very thankful!
