### ISSUE TITLE
首页在左侧菜单缩小模式下，选择菜单，样式出错

### ISSUE THREAD

**Issue by waveheart** [TaleLin/lin-cms-vue#320]
**重现步骤（可选）：**

1. 进入在线Demo， 屏幕分辨率 1920 X 1080
2. 左侧菜单缩放(窄菜单模式)。[林间有风](http://face.cms.7yue.pro/#/about)
3. 依次移入 UI => form表单 => input 此时右侧出现滚动条，滚动鼠标中轮，页面高度发生变化，样式出错
![image](https://user-images.githubusercontent.com/25602259/82531211-7aad2a00-9b71-11ea-977e-7d05141fe251.png)

**期望的结果是什么？**

浮动菜单位置不能超过页面底部

**实际的结果是什么？**

浮动菜单撑开了页面高度

**Comment by vanoneang** [comment]
感谢反馈
