### ISSUE TITLE
eslint问题

### ISSUE THREAD

**Issue by 251205668** [TaleLin/lin-cms-vue#323]
**重现步骤（可选）：**

**期望的结果是什么？**
请问那个分支的eslint标准是standard的，我拉下项目，一大片报红，koa的后端拉下来就不会有这么多eslint报错。

**实际的结果是什么？**

**Comment by SloppyJack** [comment]
这应该是IDE的问题，关闭检测就可以了。

**Comment by vanoneang** [comment]
项目使用的 ESLint 规范是 `airbnb`，可根据需要自行修改为 `standard`。

https://blog.csdn.net/weixin_47887817/article/details/106598673

**Comment by yizhitangtongxue** [comment]
![image](https://user-images.githubusercontent.com/22952680/85259709-15b06100-b49c-11ea-89ab-1b3043921d27.png)
