### ISSUE TITLE
后面会不会开源一个react的cms呢

### ISSUE THREAD

**Issue by Forest-211** [TaleLin/lin-cms-vue#332]
**描述你希望的支持的新功能？**

**你期望的 API 是怎样的？**

**Comment by vanoneang** [comment]
不会，不过好像有同学自己做了一个，你可以在GitHub搜一下。

**Comment by Bongkai** [comment]
https://github.com/Bongkai/lin-cms-react
社区开源的react版的lin-cms，欢迎使用~
