### ISSUE TITLE
关于富文本

### ISSUE THREAD

**Issue by act2009** [TaleLin/lin-cms-vue#333]
默认源代码加了 html和body标签，能否去掉呢？ 只保留`<p>111</p>`的内容，我看原版的也没有[TinyMCE](https://www.tiny.cloud/docs/demo/full-featured/)

```
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<p>1111</p>
</body>
</html>
```

**Comment by vanoneang** [comment]
@GongJS
