### ISSUE TITLE
项目打开后，头像图片为null

### ISSUE THREAD

**Issue by RocWangPeng** [TaleLin/lin-cms-vue#334]
项目打开后，头像图片为null

![Image 8](https://user-images.githubusercontent.com/23447622/87217238-9bc41700-c379-11ea-91dd-f734bf693efd.png)

**Comment by vanoneang** [comment]
用户头像是 `user` 对象中的一个属性，可以检查下 `vuex` 中的数据存储情况，如果 `avatar` 为空，采用默认头像。
![image](https://user-images.githubusercontent.com/29253688/87370109-ae766000-c5b4-11ea-972e-92795a00e5f8.png)
