### ISSUE TITLE
关于在lin-cms-vue 项目中调用 el-ui 表格里的 el-table-column 组件使用 align="center" 不居中内容，只有表头居中

### ISSUE THREAD

**Issue by liangjuncheng1995** [TaleLin/lin-cms-vue#337]
在项目中添加表格，想居中表格内容的样式
可是内容没有居中
![image](https://user-images.githubusercontent.com/30004721/88010886-818ff300-cb48-11ea-8f0c-dc396b264448.png)
![image](https://user-images.githubusercontent.com/30004721/88010939-a8e6c000-cb48-11ea-9694-893f9afaccbe.png)
不知道lin-cms-vue 里面设置了什么公共的样式造成的

**Comment by vanoneang** [comment]
感谢反馈，这地方是有问题，按下图把这块删掉就行了。
![image](https://user-images.githubusercontent.com/29253688/88063668-deb59400-cb9c-11ea-9b9e-cfe77d19d5d7.png)
