### ISSUE TITLE
希望提供sql server版本的数据库脚本

### ISSUE THREAD

**Issue by AmazingCoder2018** [TaleLin/lin-cms-vue#342]
lin-cms-dotnetcore\docs\sql 中只有Mysql的，但还是有很多程序员在使用 sql server，所以提出这样一个希望

**Comment by juzi214032** [comment]
现在mysql的脚本无法直接导入sql server 吗，我们在字段上是对sql server 做了一定兼容的

**Comment by luoyunchong** [comment]
> lin-cms-dotnetcore\docs\sql 中只有Mysql的，但还是有很多程序员在使用 sql server，所以提出这样一个希望
@AmazingCoder2018 
lin-cms-dotnetcore是我写的。。这个代码是可以自动生成表的。。你只要建个数据库，配置改一下，能直接生成sql server的表的。。
