### ISSUE TITLE
eslint 版本  导致 Cannot read property 'range' of null 错误

### ISSUE THREAD

**Issue by taoaiyi1108** [TaleLin/lin-cms-vue#346]
npm install 后启动项目报错 如图，修改 component 引入方式，问题解决， 希望7月老师团队可以测试
![image](https://user-images.githubusercontent.com/29810247/89987522-c96dea00-dcb0-11ea-8883-33463733f3a1.png)

修改后问题解决，项目完美启动
![image](https://user-images.githubusercontent.com/29810247/89987828-3f725100-dcb1-11ea-95c9-d6df92750d1c.png)
 
Google 网络解决方法 https://blog.csdn.net/weixin_42406046/article/details/103718293

PS： 大牛勿笑

**Comment by vanoneang** [comment]
这也是一种引入方式，如果遇到这个问题可以采纳。或者使用沁尘的这种[方案](https://chenjinchuang.github.io/qa/#q3%EF%BC%9Alin-cms-vue%E5%9C%A8%E8%BF%90%E8%A1%8Cnpm-run-server%E5%90%8E%E6%8F%90%E7%A4%BAcannot-read-property-range-of-null)。

**Comment by vanoneang** [comment]
根据[这条issue](https://github.com/babel/babel-eslint/issues/681)的讨论，可以尝试在 `.eslintrc ` 中添加:

```json
```

**Comment by mouday** [comment]
> 根据[这条issue](https://github.com/babel/babel-eslint/issues/681)的讨论，可以尝试在 `.eslintrc ` 中添加:
> 
> ```json
>   "rules": {
>     "template-curly-spacing": "off",
>     "indent": [
>       "warn",
>       2,
>       {
>         "ignoredNodes": ["TemplateLiteral"],
>         "SwitchCase": 1
>       }
>     ]
> }
> ```

这个可以，感谢
