### ISSUE TITLE
请求使用handleError参数,如果该请求的token出现失效,代码外侧的try catch无法捕获异常

### ISSUE THREAD

**Issue by ye-xue** [TaleLin/lin-cms-vue#365]
前端版本0.2.2

**重现步骤（可选）：**
将后端access_token失效时间设置为极短(如1秒),如果一个请求使用了handleError参数,那么最后的异常,请求外侧的try catch无法捕获
请求含{ handleError : true } -> 返回access_token失效 -> 重新发出原请求 -> 返回其他错误(前端try catch 无法捕获到该异常)

**期望的结果是什么？**
前端请求外try catch 可以捕获到 后端最后返回给前端的异常

**实际的结果是什么？**
前端能接受到异常,但是外侧的try catch 无法捕获到指定的异常

程序是可以执行到axios.js 中 reject(res) 这一行的
      // 本次请求添加 params 参数：handleError 为 true，用户自己try catch，框架不做处理
      if (params && params.handleError) {
        reject(res)
        return
      }

**Comment by vanoneang** [comment]
请参考 https://github.com/TaleLin/lin-cms-vue/blob/master/src/lin/plugin/axios.js

**Comment by ye-xue** [comment]
我现在是没有使用return new Promise(async (resolve, reject) => {}这个包裹异常处理代码,直接return的返回值,现在可以正常运行了
