### ISSUE TITLE
关于权限管理

### ISSUE THREAD

**Issue by yujiak** [TaleLin/lin-cms-vue#37]
希望隐藏掉没有获得相应权限的按钮。
比如：某个用户没有删除权限，就不显示这个删除按钮

**Comment by 7insummer** [comment]
你好。我们在设计CMS的时候 已经考虑到了，开发者可以使用Lin的核心库 Vue指令的方式 进行权限隐藏或者禁用。，很方便，具体请参考文档。

**Comment by vanoneang** [comment]
感谢反馈！

你看下这条[commit](https://github.com/TaleLin/lin-cms-vue/commit/89a4a6cbc661f2a7f9c5692fbf75f35272c99705)的相关文件处理，我们会尽快合到master。
