### ISSUE TITLE
源码的 UI 示例中，有一些跳转链接失效了

### ISSUE THREAD

**Issue by colorful3** [TaleLin/lin-cms-vue#373]
源码的 UI 示例中，有一些跳转链接失效了，有空统一检查一下吧。比如表单组合实例的 “查看源码” 按钮的跳转链接：
https://github.com/TaleLin/lin-cms-vue/blob/master/src/plugins/lin-cms-ui/views/table/TableCombo.vue
![image](https://user-images.githubusercontent.com/29156058/98189018-14656980-1f4f-11eb-82e4-fdf1e8802acf.png)

**Comment by colorful3** [comment]
@vanoneang Evan ，记得示例`demo`的那个分支也合并下哦。

**Comment by vanoneang** [comment]
> @vanoneang Evan ，记得示例`demo`的那个分支也合并下哦。

Done.
