### ISSUE TITLE
lin-table 自定义插槽

### ISSUE THREAD

**Issue by vanoneang** [TaleLin/lin-cms-vue#378]
可以参考 [https://github.com/luoyunchong/lin-cms-vue/blob/master/src/plugin/blog/view/channel/channel-list.vue](https://github.com/luoyunchong/lin-cms-vue/blob/master/src/plugin/blog/view/channel/channel-list.vue)

**Comment by gjw199513** [comment]
在lin-table加入如上代码
![image](https://user-images.githubusercontent.com/25425023/100565327-483d7000-32fe-11eb-9383-4ddea876982b.png)
`        <template slot-scope="scope">
          
          <template v-if="item.isCustom">
            <slot :name="item.prop" :row="scope.row"></slot>
          </template>
          <template v-else>
            <div>{{ scope.row[item.prop] }}</div>
          </template>
        </template>
`
需要使用的地方添加如下代码
![image](https://user-images.githubusercontent.com/25425023/100565663-137de880-32ff-11eb-8947-7a41d4581617.png)
主要是isCustom

下面就是定义的内容
![image](https://user-images.githubusercontent.com/25425023/100565763-47f1a480-32ff-11eb-98de-b243786f8abd.png)

不知道符不符合你的需求，没写的很严谨，目前可以满足我的需要，如有问题继续交流
