### ISSUE TITLE
当管理员新增完用户时，列表里明不能自动刷新出来。只能按F5刷新，重新打开

### ISSUE THREAD

**Issue by jandy0414** [TaleLin/lin-cms-vue#39]
这条想删除，但找不到删除方式

**Comment by jandy0414** [comment]
以上问题，又测试了几次,无法重现了。。
但是如下，截图，有点怪，建议添加用户，不要在第一栏的tab栏中，重复出现。
![image](https://user-images.githubusercontent.com/35617197/52161262-93d06400-26fd-11e9-9bac-3e82f3b8404a.png)

**Comment by jandy0414** [comment]
另外，建议：添加完用户，且成功时，直接像“分组管理”，自动切换换到列表页面

**Comment by vanoneang** [comment]
> 这条想删除，但找不到删除方式

是看的线上demo吗？



> 如下，截图，有点怪，建议添加用户，不要在第一栏的tab栏中，重复出现。
> ![image](https://user-images.githubusercontent.com/35617197/52161262-93d06400-26fd-11e9-9bac-3e82f3b8404a.png)

你说的第一栏tab是历史浏览记录



> 另外，建议：添加完用户，且成功时，直接像“分组管理”，自动切换换到列表页面

这个在自己开发业务时可自行处理
