### ISSUE TITLE
lin-cms-vue 怎样升级版本

### ISSUE THREAD

**Issue by jerryandlsl** [TaleLin/lin-cms-vue#394]
**描述你希望的支持的新功能？*怎样从老版本升级到最新的版本?*

**你期望的 API 是怎样的？**

**Comment by vanoneang** [comment]
工程类的开源项目不能无缝升级，如果新版本有需要的功能，可以使用 `git cherry-pick` 命令选取相应功能。或者采取[这种方案](https://vanoneang.github.io/article/#%E6%9B%B4%E6%96%B0github%E6%96%B0%E7%89%88%E6%9C%AC%E5%88%B0%E8%87%AA%E5%B7%B1%E7%9A%84%E9%A1%B9%E7%9B%AE)，但并不十分推荐。
