### ISSUE TITLE
无法正常登录

### ISSUE THREAD

**Issue by jenkinn** [TaleLin/lin-cms-vue#397]
登录界面一直跳出 ？Network error, 请检查API是否异常？对话框架，无法进行跳转到下一个页面。

![image](https://user-images.githubusercontent.com/22240132/103526403-d687b180-4ebb-11eb-9a11-ee4977c59480.png)

**Comment by vanoneang** [comment]
检查 network，调试一下 API。

**Comment by jenkinn** [comment]
> 检查 network，调试一下 API。
代码不是我写的，我是直接下载，本地服务端运行成功，怎么可能出现网络问题，代码你们写的，我上哪门子去调试
