### ISSUE TITLE
项目在ie11、360浏览器下报错

### ISSUE THREAD

**Issue by Tzcodejs** [TaleLin/lin-cms-vue#4]
**重现步骤（可选）：**

**期望的结果是什么？**

**实际的结果是什么？**

**Comment by PedroGao** [comment]
请详细描述一下你的问题

**Comment by Tzcodejs** [comment]
重现步骤（可选）：
运行IE11浏览器

期望的结果是什么？
成功打开项目。
实际的结果是什么？
页面报错。
报错信息：
chunk-vendors.833fb5f7.js (66,6702)

**Comment by vanoneang** [comment]
感谢大兄弟的PR，哈哈，就喜欢这样的开发者 /:strong

**Comment by Jokky6** [comment]
您好，对于您这次的pr，给您提出两处需要修改的地方，
1. vue.config.js中，pubilcPath:'/'这项需要去掉，否则会有如下错误：Invalid options in vue.config.js: "publicPath" is not allowed
error Command failed with exit code 1.
2. vue.config.js中，有个eslint的报错'vuex-persist'，这个字符串后面需要添加一个逗号（，）

非常感谢您的Pull requests！

**Comment by vanoneang** [comment]
感谢修复

**Comment by vanoneang** [comment]
> baseUrl不是已经废弃了吗？
> ![qq 20190128092559](https://user-images.githubusercontent.com/29053523/51809809-d26db500-22de-11e9-9a66-00f4913526fa.png)

在vue-cli3.3版本以上，用pubilcPath，项目现在的版本是3.0

**Comment by Tzcodejs** [comment]
@vanoneang OK！这个issue先不慌关，字体图标在ie下有问题。
