### ISSUE TITLE
关于tab栏的管控

### ISSUE THREAD

**Issue by jandy0414** [TaleLin/lin-cms-vue#40]
google浏览器下
当点tab右上的小图标关闭时，主舞台未一同消失关没了

**期望的结果是什么？**
tab栏的标题与主舞台内容，一起消失

**实际的结果是什么？**
tab栏的标题消失了，而主舞台内容还在

**Comment by jandy0414** [comment]
补充操作步骤：从左边开始关时

**Comment by vanoneang** [comment]
很好的建议，感谢反馈

**Comment by vanoneang** [comment]
现在这种单页应用的模式跟传统的服务端渲染的不同，浏览记录中记录的只是一些组件的路由信息，并没有真实的页面。

**Comment by GongJS** [comment]
tab栏只记录用户访问过的页面路由地址，方便用户跳转。
