### ISSUE TITLE
有刷新舞台的API吗？ 

### ISSUE THREAD

**Issue by gomez44944** [TaleLin/lin-cms-vue#401]
**描述你希望的支持的新功能？**
有时候需要手动刷新舞台里的内容 ，有这样的api 吗？
**你期望的 API 是怎样的？**

**Comment by gomez44944** [comment]
我需要在nav-bar 里手动刷新舞台

**Comment by vanoneang** [comment]
> 我需要在nav-bar 里手动刷新舞台

没太明白，能说下具体场景吗？

**Comment by gomez44944** [comment]
点击中英文切换 刷新下面的banner列表



---原始邮件---
发件人: "Evan Wang"<notifications@github.com&gt;
发送时间: 2021年1月6日(周三) 中午11:37
收件人: "TaleLin/lin-cms-vue"<lin-cms-vue@noreply.github.com&gt;;
抄送: "gomez44944"<591470459@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [TaleLin/lin-cms-vue] 有刷新舞台的API吗？  (#401)




  
我需要在nav-bar 里手动刷新舞台
  
没太明白，能说下具体场景吗？

**Comment by vanoneang** [comment]
抱歉，目前是不支持国际化的，大部分用户用不上这个功能。

如果想要实现点击切换语言，可以参考[vue-i18n](https://github.com/kazupon/vue-i18n)这个库和 vue-element-admin [i18n](https://github.com/PanJiaChen/vue-element-admin/tree/i18n)分支。

**Comment by gomez44944** [comment]
我已经可以国际化了 就是想手动刷新一下舞台组件 有这样api吗？



---原始邮件---
发件人: "Evan Wang"<notifications@github.com&gt;
发送时间: 2021年1月6日(周三) 中午12:34
收件人: "TaleLin/lin-cms-vue"<lin-cms-vue@noreply.github.com&gt;;
抄送: "gomez44944"<591470459@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [TaleLin/lin-cms-vue] 有刷新舞台的API吗？  (#401)




 
抱歉，目前是不支持国际化的，大部分用户用不上这个功能。
 
如果想要实现点击切换语言，可以参考vue-i18n这个库和 vue-element-admin i18n分支。

**Comment by vanoneang** [comment]
没有的。

**Comment by gomez44944** [comment]
已解决！
