### ISSUE TITLE
文件上传 加上登录限制 卡死

### ISSUE THREAD

**Issue by jia1076999758** [TaleLin/lin-cms-vue#402]
**重现步骤（可选）：**
在文件上传接口加上登录限制
![image](https://user-images.githubusercontent.com/41228756/103738937-c85aa200-502f-11eb-816e-1d6f37ec0831.png)

**期望的结果是什么？**
上传成功
**实际的结果是什么？**
![image](https://user-images.githubusercontent.com/41228756/103739046-fc35c780-502f-11eb-806f-c8ae973fd026.png)
![image](https://user-images.githubusercontent.com/41228756/103739138-25565800-5030-11eb-8432-122bbb431666.png)
![image](https://user-images.githubusercontent.com/41228756/103739199-3ef79f80-5030-11eb-9549-fbec8af033c6.png)

**Comment by jetBn** [comment]
不想理你

**Comment by smileShirmy** [comment]
想问下你的Node版本是多少？如果是版本14或以上可能会有这个问题，试试使用 v12 版本的 node，可以使用 nvm 同时管理多个版本的 node

**Comment by jia1076999758** [comment]
> 想问下你的Node版本是多少？如果是版本14或以上可能会有这个问题，试试使用 v12 版本的 node，可以使用 nvm 同时管理多个版本的 node

感谢 v12版本好使
