### ISSUE TITLE
当删除分组时，且这个分组下有用户时，页面一直停留在转圈圈的状态

### ISSUE THREAD

**Issue by jandy0414** [TaleLin/lin-cms-vue#42]
如题，导致页面无法继续

**Comment by jandy0414** [comment]
附图：
![image](https://user-images.githubusercontent.com/35617197/52161138-a6e23480-26fb-11e9-96b6-f117b4387f8c.png)

**Comment by vanoneang** [comment]
可以参考下develop分支下的相关代码，这块已经优化过了。
