### ISSUE TITLE
update deps: 建议升级 node-sass 依赖版本

### ISSUE THREAD

**Issue by sunlin92** [TaleLin/lin-cms-vue#426]
当前master分支依赖的 node-sass 4.12.0 在编译安装时需要Python2环境。
Python2的生命周期已经结束， 希望升级到支持Python3编译的版本。

**Comment by vanoneang** [comment]
node-sass 4.12.0可以使用 node12 及以下版本进行安装，针对 node14 可做降级处理。

**Comment by vanoneang** [comment]
升级版本为 `"node-sass": "^5.0.0",  "sass-loader": "^10.1.0",` 后，会出现循环引用的报错，还未想到解决方案。

**Comment by azhen98** [comment]
### 建议将 node-sass的依赖改为 `4.13.1` 
### 改为4.13.1后不在提示 建议升级
### 5.0版本 基于node15 的版于
