### ISSUE TITLE
日志管理--优化建议

### ISSUE THREAD

**Issue by jandy0414** [TaleLin/lin-cms-vue#43]
按人员的查询时，查询出来后，列表栏，建议显中，已选项。
如下图的super建议显示出来：
![image](https://user-images.githubusercontent.com/35617197/52161408-84eab100-26ff-11e9-94a1-a246fdf1e9b5.png)

**Comment by vanoneang** [comment]
很好的建议，感谢反馈

**Comment by vanoneang** [comment]
已处理
