### ISSUE TITLE
执行npm install 报错

### ISSUE THREAD

**Issue by zhangqi4095** [TaleLin/lin-cms-vue#432]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: lin-cms@0.3.6
npm ERR! Found: eslint@6.7.2
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^6.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.0.0" from eslint-plugin-vue@5.2.3
npm ERR! node_modules/eslint-plugin-vue
npm ERR!   dev eslint-plugin-vue@"^5.2.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/zhangqi/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zhangqi/.npm/_logs/2021-03-17T13_06_32_535Z-debug.log

**Comment by zzheng2020** [comment]
执行`npm install`之后，一开始有`gyp: No Xcode or CLT version detected! `这样的报错吗？
如果有，尝试依次执行：
- `sudo rm -rf $(xcode-select -p)`
- `sudo xcode-select --install`
遇到同意条款全部选同意，然后再`npm install`

如果没有。。。sorry orz

**Comment by zzheng2020** [comment]
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: lin-cms@0.3.6
> npm ERR! Found: eslint@6.7.2
> npm ERR! node_modules/eslint
> npm ERR! dev eslint@"^6.0.1" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer eslint@"^5.0.0" from eslint-plugin-vue@5.2.3
> npm ERR! node_modules/eslint-plugin-vue
> npm ERR! dev eslint-plugin-vue@"^5.2.3" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR! See /home/zhangqi/.npm/eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /home/zhangqi/.npm/_logs/2021-03-17T13_06_32_535Z-debug.log

执行`npm install`之后，一开始有`gyp: No Xcode or CLT version detected! `这样的报错吗？
如果有，尝试依次执行：
- `sudo rm -rf $(xcode-select -p)`
- `sudo xcode-select --install`
遇到同意条款全部选同意，然后再`npm install`

如果没有。。。sorry orz

**Comment by zzheng2020** [comment]
执行`npm install`之后，一开始有`gyp: No Xcode or CLT version detected! `这样的报错吗？
如果有，尝试依次执行：
- `sudo rm -rf $(xcode-select -p)`
- `sudo xcode-select --install`
遇到同意条款全部选同意，然后再`npm install`

如果没有。。。sorry orz
