### ISSUE TITLE
axios 如何设置请求失败次数和请求失败重试间隔

### ISSUE THREAD

**Issue by gomez44944** [TaleLin/lin-cms-vue#456]
**描述你希望的支持的新功能？**
![image](https://user-images.githubusercontent.com/7356966/118347356-39c5d680-b575-11eb-91f1-688e05cd09c4.png)

**你期望的 API 是怎样的？**

**Comment by vanoneang** [comment]
这个是特别早期的一个设计，注释忘记删除了。目前的重试机制是只会重发一次请求，加上原始请求两次都是失败的情况再多次重发也没有意义。

**Comment by gomez44944** [comment]
了解，感谢！



---原始邮件---
发件人: "Evan ***@***.***&gt;
发送时间: 2021年5月18日(周二) 晚上10:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TaleLin/lin-cms-vue] axios 如何设置请求失败次数和请求失败重试间隔 (#456)




 
这个是特别早期的一个设计，注释忘记删除了。目前的重试机制是只会重发一次请求，加上原始请求两次都是失败的情况再多次重发也没有意义。
