### ISSUE TITLE
请问lin-cms-vue支持keepalive设置页面缓存吗？

### ISSUE THREAD

**Issue by tongtongking** [TaleLin/lin-cms-vue#478]
我看到之前也有人提到过切换table时页面数据重新加载的问题，这个应该是页面没有进行缓存导致的数据重复请求，我看到vue内置组件keep-alive是支持页面缓存的，但是我在参考了https://segmentfault.com/a/1190000019610283 配置之后不能生效，请问是框架不支持keep-alive缓存还是我配置的原因？配置如图：
![image](https://user-images.githubusercontent.com/17446323/123137712-d9388c00-d486-11eb-8682-b5e138b90447.png)
![image](https://user-images.githubusercontent.com/17446323/123137820-fc633b80-d486-11eb-82d3-47bdd8a71e50.png)

**Comment by vanoneang** [comment]
如下图：
![image](https://user-images.githubusercontent.com/29253688/123189687-db273d00-d4d0-11eb-9dc9-ff191cf6b317.png)

请注意，如果使用了 keep-alive 缓存页面，需要实时更新数据的页面请配合 `activated` 钩子使用。

**Comment by tongtongking** [comment]
感谢您的及时回复，我去掉include="CustomerList"就能全部生效，加上就全部不生效是因为没有配合activated钩子函数的原因吗？我也会再进一步学习一下配合钩子函数进行页面缓存控制

**Comment by vanoneang** [comment]
`CustomerList` 是我自己的业务逻辑，你可以看下相关文档学习 `include` 的用法。
