### ISSUE TITLE
您好，可以提供下那个真实案例吗，有些东西不太会用，想借鉴一下 谢谢

### ISSUE THREAD

**Issue by 1535050440** [TaleLin/lin-cms-vue#492]
http://sleeve.talelin.com/#/about
您好，可以提供下那个真实案例的源代码吗，有些东西不太会用，想借鉴一下 谢谢

**Comment by vanoneang** [comment]
> http://sleeve.talelin.com/#/about
> 您好，可以提供下那个真实案例的源代码吗，有些东西不太会用，想借鉴一下 谢谢

这个项目有商业版权，不能开源使用。
