### ISSUE TITLE
项目在Firefox、Edge浏览器下显示异常

### ISSUE THREAD

**Issue by Tzcodejs** [TaleLin/lin-cms-vue#5]
**实际的结果是什么？**
1. 右上角X未显示
![qq 20190118152825](https://user-images.githubusercontent.com/29053523/51371710-ef172980-1b35-11e9-87ac-b8c3b7b66706.png)
2. 按钮文字未垂直居中
![button](https://user-images.githubusercontent.com/29053523/51372588-aca31c00-1b38-11e9-952c-cb2f83206a42.png)
3. 按钮出现1px白边
![1px](https://user-images.githubusercontent.com/29053523/51372779-42d74200-1b39-11e9-8e79-f5966d59a187.png)
4. 删除按钮点击取消后出现虚线（Edge）
![red](https://user-images.githubusercontent.com/29053523/51372859-8467ed00-1b39-11e9-8fb7-08f3fde7864b.png)
5. textarea高度失效，在Firefox下拖拉有明显迟滞感，Edge无法拖拉
![textarea](https://user-images.githubusercontent.com/29053523/51373355-03115a00-1b3b-11e9-9f87-94ece3c9a3d8.png)

**Comment by vanoneang** [comment]
感谢反馈 @GongJS

**Comment by vanoneang** [comment]
感谢修复
