### ISSUE TITLE
createWebHistory路由模式不显示自定义图标

### ISSUE THREAD

**Issue by amorphis666** [TaleLin/lin-cms-vue#509]
0.4.0版本路由设置由 history: createWebHashHistory() 改为 createWebHistory() 后不显示自定义图标，如菜单栏左侧图标无法显示

**Comment by vanoneang** [comment]
自定义图标不显示一般与 iconfont 加载相关，有时网络异常会造成不能正常加载情况。此现象与路由配置无关。

![image](https://user-images.githubusercontent.com/29253688/136740170-b135e3b4-4819-4cd8-b0b3-318e208e95f1.png)
