### ISSUE TITLE
Invalid options in vue.config.js: "publicPath" is not allowed

### ISSUE THREAD

**Issue by PedroGao** [TaleLin/lin-cms-vue#51]
**重现步骤（可选）：**
clone下来的本地仓库的vue-cli的版本为`^3.0.1`，但是publicPath在`^3.2.0`才得到支持，因此请升级或者修改相应的配置。

**Comment by vanoneang** [comment]
感谢反馈！

publicPath在vue-cli3.3以上才可以使用，改为baseUrl即可

这个后续会将版本升级。
