### ISSUE TITLE
在后台新加一个用户，登录后用户组还是超级管理员

### ISSUE THREAD

**Issue by NightMingGit** [TaleLin/lin-cms-vue#517]
**重现步骤（可选）：**

**期望的结果是什么？**

**实际的结果是什么？**

**Comment by vanoneang** [comment]
添加用户时如果不选分组，默认是归为游客组，可以看下数据表的数据是否有什么异常。

**Comment by NightMingGit** [comment]
![image](https://user-images.githubusercontent.com/92633021/141594236-b6799b93-97cc-4af2-8bce-39841ab1057e.png)
右上角的文字 我指的是，我看了好像是用户信息没有返回gropuname

**Comment by NightMingGit** [comment]
> 添加用户时如果不选分组，默认是归为游客组，可以看下数据表的数据是否有什么异常。

我截图了

**Comment by gadfly3173** [comment]
https://github.com/TaleLin/lin-cms-vue/blob/c473df2db5fed465f938990399f2746cc9492983/src/component/layout/user.vue#L17-L29

https://github.com/TaleLin/lin-cms-vue/blob/fda48a96129b09d7824da83deef4b09d96c14f3d/src/component/layout/user.vue#L16-L28

这地方是vue3版加出来的，本来也没有。lin-cms本身角色也不是只能绑定单个的，不如还是删了

**Comment by NightMingGit** [comment]
> https://github.com/TaleLin/lin-cms-vue/blob/c473df2db5fed465f938990399f2746cc9492983/src/component/layout/user.vue#L17-L29
> 
> https://github.com/TaleLin/lin-cms-vue/blob/fda48a96129b09d7824da83deef4b09d96c14f3d/src/component/layout/user.vue#L16-L28
> 
> 这地方是vue3版加出来的，本来也没有。lin-cms本身角色也不是只能绑定单个的，不如还是删了

不要也行
