### ISSUE TITLE
axios response interceptor 响应拦截器失效

### ISSUE THREAD

**Issue by sunlin92** [TaleLin/lin-cms-vue#527]
代码文件 **/src/lin/plugin/axios.js** 102行 

 _axios.interceptors.response.use 中的逻辑不生效

**Comment by gadfly3173** [comment]
看起来好像没什么问题？这个文件也没有大改过吧，我自己用的时候没遇到什么问题

**Comment by NightMingGit** [comment]
有demo吗

**Comment by sunlin92** [comment]
是axios版本的问题，升级后bug消失

axios/axios#4012
