### ISSUE TITLE
 0.4.0 升级到0.4.2   php 后端 ，升级后报跨域

### ISSUE THREAD

**Issue by zhangchenguang231x** [TaleLin/lin-cms-vue#530]
解决办法：
升级后，报跨域问题，检查后发现请求头中增加了tag属性。需要在tp5框架的跨域允许发请求头中增加tag属性；
请问：
前端加上tag属性是做什么用的啊？

**Comment by vanoneang** [comment]
`tag` 是在验证码功能中添加的，tag 首先由后端根据验证码和秘钥算出，然后登录时通过这个字段校验验证码是否正确。
