### ISSUE TITLE
游客分组登录后，显示的是超级管理员？

### ISSUE THREAD

**Issue by HEXACC** [TaleLin/lin-cms-vue#566]
**重现步骤（可选）：**
注册游客用户，登录。
**期望的结果是什么？**
个人中心卡片显示分组为：游客
**实际的结果是什么？**
个人中心卡片显示分组为：超级管理员

**Comment by vanoneang** [comment]
#567 目前版本一个人可以同时在多个分组，这行可以删掉了。
