### ISSUE TITLE
文档开源问题

### ISSUE THREAD

**Issue by ronething** [TaleLin/lin-cms-vue#64]
**描述你希望的支持的新功能？**

请问文档开源不 📝 
http://doc.cms.7yue.pro

**Comment by vanoneang** [comment]
你好，文档的源码可以放到个人仓库供大家学习使用，但是暂时没有精力作为开源产品去维护

**Comment by ronething** [comment]
> 你好，文档的源码可以放到个人仓库供大家学习使用，但是暂时没有精力作为开源产品去维护

好的。那希望可以开放出来供大家学习。谢谢。

**Comment by vanoneang** [comment]
@ronething  [link](https://github.com/vanoneang/blog/tree/lin)
