### ISSUE TITLE
时间戳问题

### ISSUE THREAD

**Issue by ronething** [TaleLin/lin-cms-vue#69]
> 初学前端可以否教一下时间戳转换

![image](https://user-images.githubusercontent.com/28869910/54044497-10c59080-420a-11e9-883f-03c3321bbbd0.png)

```javascript
 tableColumn: [{
        prop: 'title',
        label: '标题',
      },{
        prop: 'create_time', // 这里不知道如何变换？
        label: '创建日期',
      }],
```

看到在 `Log.vue` 中可以 `{{log.time | dateTimeFormatter}}`

想知道在表格这里如何操作？
虽然问题很蠢但还是希望可以收到回复。谢谢。

**Comment by ronething** [comment]
fix.

**Comment by xiaoyunjie** [comment]
@ronething 你提出的这个问题，被你自己fix，请问你后来是怎么解决的，分享一下
