### ISSUE TITLE
Lin-CMS的前端bug-添加图书

### ISSUE THREAD

**Issue by zhuxiaoluxiaonuan** [TaleLin/lin-cms-vue#7]
添加图书成功之后，点击查看图书列表，没有显示新增图书，只有再次刷新界面时，才会显示最新添加的图书

**Comment by PedroGao** [comment]
由于前端是SPA应用，因此发生路由切换的时候并不会引起页面重新渲染。
这不是bug，我们会在后续优化这一体验的。感谢反馈。
