### ISSUE TITLE
官网格式有问题

### ISSUE THREAD

**Issue by gaojx97** [TaleLin/lin-cms-vue#71]
**重现步骤（可选）：**
[linCMS](http://doc.cms.7yue.pro/) 官网下面 

**期望的结果是什么？**
下面重复了一些无格式内容，应该没有下面的内容

**实际的结果是什么？**
![image](https://user-images.githubusercontent.com/15071824/54099571-ef74c800-43f4-11e9-9a3e-c8f07e92d48a.png)

**Comment by quanquan2100** [comment]
文档问题已修复

**Comment by gaojx97** [comment]
get了，麻烦作者
