### ISSUE TITLE
首页登录提示问题

### ISSUE THREAD

**Issue by ronething** [TaleLin/lin-cms-vue#72]
**重现步骤（可选）：**
![image](https://user-images.githubusercontent.com/28869910/54171241-a8e6a280-44b4-11e9-854c-a5c65d1b2c66.png)

这个填写用户登录是不是写错了。

**Comment by Jokky6** [comment]
是的，多谢反馈！

**Comment by Jokky6** [comment]
已经修复，暂时还没有合并到主分支，谢谢反馈。给您带来的不良体验，敬请谅解！谢谢

**Comment by ronething** [comment]
没有不良哈哈 我自己改了 只是觉得没有必要混 pr 所以提一下。
