### ISSUE TITLE
refreshToken 设计的安全漏洞

### ISSUE THREAD

**Issue by runzx** [TaleLin/lin-cms-vue#76]
**重现步骤（可选）：**
  我们的lin-cms-vue 的accessToken refreshToken都保存在pc端windows.Cookies里，并且周期超过浏览器周期，这样会关闭浏览器后refreshToken 仍然存在当地硬盘，这样设计安全方面是不是有漏洞？
**期望的结果是什么？**
  我觉得refreshToken不应缓存当地，直接放在state 内存里，退出就清除才安全。
**实际的结果是什么？**

**Comment by vanoneang** [comment]
在 config/index.js 中，有配置项是否在无操作后，定时跳出登录，在跳出登录的时候清空了token

![image](https://user-images.githubusercontent.com/29253688/54904027-4eb7f980-4f18-11e9-88e8-53d1fdc1d4bc.png)

**Comment by vanoneang** [comment]
有些代码还没合到master分支，本周就差不多了，感谢

**Comment by runzx** [comment]
我有个建议，把这2个token存到 sessionStorage中，这样浏览器关闭时自动清除，保障安全性。

**Comment by vanoneang** [comment]
目前是放到了 localstorage ，一般场景已登录过的，关闭浏览器后重开是不需要重新登录的，为了安全考虑可以在自己的项目里自行决定储存方式。
