### ISSUE TITLE
关于表格实例点击取消推荐时，一直处于加载状态

### ISSUE THREAD

**Issue by zhuxiaoluxiaonuan** [TaleLin/lin-cms-vue#77]
**重现步骤（可选）：**
点击左侧表格实例
点击右侧表格第一栏推荐
第一次点击，显示推荐成功
再次点击
**期望的结果是什么？**
取消推荐
**实际的结果是什么？**
一直处于加载状态
![@~FO6LI(QPAUO(1ZJ7VR%QS](https://user-images.githubusercontent.com/39010432/55208575-9771fa00-5219-11e9-8444-1867d03ec1f6.png)

**Comment by GongJS** [comment]
已修复
