### ISSUE TITLE
关于表格示例中，备注列中的确定修改按钮和取消按钮被遮挡的问题

### ISSUE THREAD

**Issue by zhuxiaoluxiaonuan** [TaleLin/lin-cms-vue#78]
**重现步骤（可选）：**
点击左侧表格示例
点击右侧表格中第一行的编辑按钮
第一行备注栏显示可编辑按钮
**期望的结果是什么？**
点击确定修改按钮或者取消修改的按钮
**实际的结果是什么？**
两个按钮被遮挡，无法点击
![image](https://user-images.githubusercontent.com/39010432/55208794-7eb61400-521a-11e9-83c6-05fdb59258e5.png)

**Comment by GongJS** [comment]
这个列表可以左右滚动的
