### ISSUE TITLE
关于表格示例中，取消某些列显示时，表格排列异常的问题

### ISSUE THREAD

**Issue by zhuxiaoluxiaonuan** [TaleLin/lin-cms-vue#79]
**重现步骤（可选）：**
点击左侧表格示例
点击右侧列操作
选中排名，其余列取消选中
**期望的结果是什么？**
表格显示正常，电影名与排名两列的距离显示正常
**实际的结果是什么？**
表格显示异常，电影名与排名两列的距离异常
![0HJ{6PBY74KNKPDOBZZ5SR6](https://user-images.githubusercontent.com/39010432/55208992-6a264b80-521b-11e9-8696-3000f4327982.png)

**Comment by GongJS** [comment]
这个列的宽度是自适应的，剩下显示的列默认会占据表格剩下的宽度
