### ISSUE TITLE
关于Lin-CMS-图书管理功能

### ISSUE THREAD

**Issue by zhuxiaoluxiaonuan** [TaleLin/lin-cms-vue#8]
在图书列表里面
1. 新增查看图书详情功能
因为仅凭书名和作者信息，管理员可能无法确定是否需要重新编辑，
2. 新增搜索图书功能
方便管理员更快地对图书进行定位

**Comment by vanoneang** [comment]
**感谢反馈！**

细节方面我们会尽快优化，让用户体验更加友好，谢谢

另外，借着这个 issue 说明一下，希望大家通过这个简单的 demo 能够了解到 lin-cms-vue 是怎么实现：
1. 将业务模型相关的模型层封装
2. 怎样全局处理 API 异常
3. 怎样完成路由级别的权限控制和 API 级别的权限控制
4. 等等。。。

希望借助这个开源项目和大家一同成长 😁
