### ISSUE TITLE
【BUG】点击链接跳转页面tab栏没有同步显示

### ISSUE THREAD

**Issue by gaojx97** [TaleLin/lin-cms-vue#86]
**重现步骤（可选）：**
![image](https://user-images.githubusercontent.com/15071824/55289083-32bec700-53f4-11e9-9ca1-936ae32158f2.png)
点击这个部分跳转之后，页面上方没有高亮

**期望的结果是什么？**
应该有变色
![image](https://user-images.githubusercontent.com/15071824/55289095-49651e00-53f4-11e9-9b08-509df7a82ef3.png)

**实际的结果是什么？**
![image](https://user-images.githubusercontent.com/15071824/55289090-42d6a680-53f4-11e9-88b3-41d14bfc1c9e.png)

**Comment by vanoneang** [comment]
好的，感谢反馈

**Comment by vanoneang** [comment]
已处理
