### ISSUE TITLE
权限管理栏，点击相应菜单拖动页面挡住按钮后，点其他菜单后页面没有重置回顶部

### ISSUE THREAD

**Issue by yujiak** [TaleLin/lin-cms-vue#9]
**重现步骤（可选）：**
进入用户列表或分组管理页面，向下滚动页面挡住“添加用户”等按钮后，再点击“分组管理”菜单，页面未重置回顶部。导致按钮被遮挡。（咋一看误以为没添加功能~_~）
![default](https://user-images.githubusercontent.com/17984724/51423897-66fe5600-1c01-11e9-8c70-7b660745991d.jpg)

**期望的结果是什么？**
点击左侧菜单，右侧页面重置回顶部

**实际的结果是什么？**
目前是保持在上一个页面的位置

**Comment by GongJS** [comment]
该问题已解决，记得更新下代码哈。
